// This file is @generated by prost-build.
/// Control message is used to control the tunnel.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ControlStream {
    #[prost(enumeration = "Command", tag = "1")]
    pub command: i32,
    #[prost(oneof = "control_stream::Payload", tags = "2, 3")]
    pub payload: ::core::option::Option<control_stream::Payload>,
}
/// Nested message and enum types in `ControlStream`.
pub mod control_stream {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "2")]
        Hello(super::HelloPayload),
        #[prost(message, tag = "3")]
        Work(super::WorkPayload),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HelloPayload {
    #[prost(string, tag = "1")]
    pub server_version: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub your_entrypoint: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkPayload {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrafficStream {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterReq {
    #[prost(message, optional, tag = "1")]
    pub tunnel: ::core::option::Option<Tunnel>,
}
/// Each tunnel is a bidirectional connection between the client and the server.
/// Basically, one tunnel corresponds to one http2 connection.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tunnel {
    /// id is the unique identifier of the tunnel,
    /// it's assigned by the server.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// name is the name of the tunnel.
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "tunnel::Type", tag = "3")]
    pub r#type: i32,
    #[prost(oneof = "tunnel::Config", tags = "4, 5")]
    pub config: ::core::option::Option<tunnel::Config>,
}
/// Nested message and enum types in `Tunnel`.
pub mod tunnel {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Type {
        Tcp = 0,
        Http = 10,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Type::Tcp => "TCP",
                Type::Http => "HTTP",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "TCP" => Some(Self::Tcp),
                "HTTP" => Some(Self::Http),
                _ => None,
            }
        }
    }
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Config {
        #[prost(message, tag = "4")]
        Http(super::HttpConfig),
        #[prost(message, tag = "5")]
        Tcp(super::TcpConfig),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpConfig {
    #[prost(oneof = "http_config::Mode", tags = "1, 2, 3")]
    pub mode: ::core::option::Option<http_config::Mode>,
}
/// Nested message and enum types in `HTTPConfig`.
pub mod http_config {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Mode {
        /// the server starts to listen on the remote_port.
        #[prost(int32, tag = "1")]
        RemotePort(i32),
        #[prost(string, tag = "2")]
        Subdomain(::prost::alloc::string::String),
        /// the server's public domain is <https://tunneld.dev,>
        /// you may configure a subdomain <https://monitor.tunneld.dev,>
        /// then the request matches the subdomain will be forwarded to the related tunnel.
        #[prost(string, tag = "3")]
        Domain(::prost::alloc::string::String),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TcpConfig {
    #[prost(int32, tag = "1")]
    pub remote_port: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnRegisterReq {
    /// id is the tunnel id.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnRegisteredResp {}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Command {
    /// Hello command is sent only once as the first control message to the client.
    Hello = 0,
    /// Work command is sent when a user connection is established,
    /// then the client needs to start a Data stream to receive and send data.
    Work = 1,
}
impl Command {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Command::Hello => "HELLO",
            Command::Work => "Work",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "HELLO" => Some(Self::Hello),
            "Work" => Some(Self::Work),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod tunnel_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    #[derive(Debug, Clone)]
    pub struct TunnelServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl TunnelServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> TunnelServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> TunnelServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<http::Request<tonic::body::BoxBody>>>::Error:
                Into<StdError> + Send + Sync,
        {
            TunnelServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// the client sends Register to the server to create a tunnel.
        /// the server returns a stream Control to the client, the following control messages are sent through the stream.
        pub async fn register(
            &mut self,
            request: impl tonic::IntoRequest<super::RegisterReq>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ControlStream>>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/message.TunnelService/Register");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("message.TunnelService", "Register"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Unregister provides a graceful way to close a tunnel if the client wants to close.
        pub async fn un_register(
            &mut self,
            request: impl tonic::IntoRequest<super::UnRegisterReq>,
        ) -> std::result::Result<tonic::Response<super::UnRegisteredResp>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/message.TunnelService/UnRegister");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("message.TunnelService", "UnRegister"));
            self.inner.unary(req, path, codec).await
        }
        /// server side: write data to the traffic stream, and read data from the traffic stream.
        /// client side: read data from the traffic stream, and write data to the traffic stream.
        pub async fn data(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::TrafficStream>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::TrafficStream>>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/message.TunnelService/Data");
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("message.TunnelService", "Data"));
            self.inner.streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod tunnel_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with TunnelServiceServer.
    #[async_trait]
    pub trait TunnelService: Send + Sync + 'static {
        /// Server streaming response type for the Register method.
        type RegisterStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ControlStream, tonic::Status>,
            > + Send
            + 'static;
        /// the client sends Register to the server to create a tunnel.
        /// the server returns a stream Control to the client, the following control messages are sent through the stream.
        async fn register(
            &self,
            request: tonic::Request<super::RegisterReq>,
        ) -> std::result::Result<tonic::Response<Self::RegisterStream>, tonic::Status>;
        /// Unregister provides a graceful way to close a tunnel if the client wants to close.
        async fn un_register(
            &self,
            request: tonic::Request<super::UnRegisterReq>,
        ) -> std::result::Result<tonic::Response<super::UnRegisteredResp>, tonic::Status>;
        /// Server streaming response type for the Data method.
        type DataStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::TrafficStream, tonic::Status>,
            > + Send
            + 'static;
        /// server side: write data to the traffic stream, and read data from the traffic stream.
        /// client side: read data from the traffic stream, and write data to the traffic stream.
        async fn data(
            &self,
            request: tonic::Request<tonic::Streaming<super::TrafficStream>>,
        ) -> std::result::Result<tonic::Response<Self::DataStream>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct TunnelServiceServer<T: TunnelService> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: TunnelService> TunnelServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(inner: T, interceptor: F) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for TunnelServiceServer<T>
    where
        T: TunnelService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/message.TunnelService/Register" => {
                    #[allow(non_camel_case_types)]
                    struct RegisterSvc<T: TunnelService>(pub Arc<T>);
                    impl<T: TunnelService> tonic::server::ServerStreamingService<super::RegisterReq>
                        for RegisterSvc<T>
                    {
                        type Response = super::ControlStream;
                        type ResponseStream = T::RegisterStream;
                        type Future =
                            BoxFuture<tonic::Response<Self::ResponseStream>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RegisterReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TunnelService>::register(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = RegisterSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/message.TunnelService/UnRegister" => {
                    #[allow(non_camel_case_types)]
                    struct UnRegisterSvc<T: TunnelService>(pub Arc<T>);
                    impl<T: TunnelService> tonic::server::UnaryService<super::UnRegisterReq> for UnRegisterSvc<T> {
                        type Response = super::UnRegisteredResp;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UnRegisterReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TunnelService>::un_register(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = UnRegisterSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/message.TunnelService/Data" => {
                    #[allow(non_camel_case_types)]
                    struct DataSvc<T: TunnelService>(pub Arc<T>);
                    impl<T: TunnelService> tonic::server::StreamingService<super::TrafficStream> for DataSvc<T> {
                        type Response = super::TrafficStream;
                        type ResponseStream = T::DataStream;
                        type Future =
                            BoxFuture<tonic::Response<Self::ResponseStream>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::TrafficStream>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut =
                                async move { <T as TunnelService>::data(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = DataSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => Box::pin(async move {
                    Ok(http::Response::builder()
                        .status(200)
                        .header("grpc-status", "12")
                        .header("content-type", "application/grpc")
                        .body(empty_body())
                        .unwrap())
                }),
            }
        }
    }
    impl<T: TunnelService> Clone for TunnelServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: TunnelService> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: TunnelService> tonic::server::NamedService for TunnelServiceServer<T> {
        const NAME: &'static str = "message.TunnelService";
    }
}
